### ISSUE TITLE
Нет работы с несколькими контейнерами

### ISSUE THREAD

**Issue by MariaNosareva** [uta1/registration_confirm#1]
Вы попытались впихнуть всё в один контейнер, что не нужно было делать. Должно быть минимум три разных контейнера: кролик, само приложение и отправщик писем

**Comment by uta1** [comment]
Привет! Мы вроде всё сделали, но, кажется, что-то с портами не так, и мы не можем разобраться :( Сервер запускается, но подключиться не можем. consumer не может подключиться к rabbitmq. Просим помощи :(

**Comment by uta1** [comment]
Работает :)
